import Head from "next/head"
import { useQuery } from "urql"
import { PRODUCT_QUERY } from "../lib/query"
import Product from "../components/Product"
import { Gallery } from "../styles/Gallery"
import Nav from "../components/Nav"

export default function Home() {
  const [{ data, fetching, error }] = useQuery({ query: PRODUCT_QUERY })
  if (fetching) return <p>Loading...</p>
  if (error) return <p>Oh... {error.message}</p>
  const products = data.products.data
  return (
    <div>
      <Head>
        <title>e-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </div>
  )
}
